#include <stdio.h>
#include <string.h>
#include <fips204.h>

int main(int argc, const char **argv) {
  MLDSA_public_key pub;
  MLDSA_private_key priv;
  MLDSA_public_key pub_2;
  MLDSA_private_key priv_2;
  MLDSA_signature sig;
  MLDSA_signature sig_2;
  ml_dsa_seed seed;
  ml_dsa_err err;
  MLDSA_public_key pub_weird;
  MLDSA_private_key priv_weird;

  const uint8_t msg[] = "wfwfwf";
  const uint8_t ctx[] = "testing";
  const uint8_t badmsg[] = "ffffff";
  const uint8_t badctx[] = "badctx";
  const size_t msglen = 6;
  const size_t ctxlen = 7;
  const size_t badctxlen = 6;
  const size_t badmsglen = 6;

  memset (&seed, 0, sizeof(seed));

  /* ensure that seed-based generation is deterministic */
  if (MLDSA_keygen_from_seed (&seed, &pub, &priv))
    return 1;
  if (MLDSA_keygen_from_seed (&seed, &pub_2, &priv_2))
    return 1;
  if (memcmp(&pub, &pub_2, sizeof(pub))) {
    fprintf (stderr, "public keys generated by seed did not match\n");
    return 5;
  }

  if (memcmp(&priv, &priv_2, sizeof(priv))) {
    fprintf (stderr, "private keys generated by seed did not match\n");
    return 6;
  }

  if (MLDSA_keygen (&pub, &priv))
      return 1;

  printf("Public (%d): ", MLDSA_size);
  for (int n = 0; n < sizeof(pub.data); n++)
    printf ("%02x ", pub.data[n]);
  printf("\n");
  
  printf("Private (%d): ", MLDSA_size);
  for (int n = 0; n < sizeof(priv.data); n++)
    printf ("%02x ", priv.data[n]);
  printf("\n");

  if (MLDSA_sign (&priv, msg, msglen, ctx, ctxlen, &sig))
    return 2;
  if (MLDSA_sign (&priv, msg, msglen, ctx, ctxlen, &sig_2))
    return 2;

  if (!memcmp(&sig, &sig_2, sizeof(sig))) {
    fprintf (stderr, "Hedged signatures match; they should use entropy\n");
    return 6;
  }
  if (MLDSA_verify (&pub, &sig, msg, msglen, ctx, ctxlen)) {
    fprintf (stderr, "verify sig failed!\n");
    return 7;
  }
  if (MLDSA_verify (&pub, &sig_2, msg, msglen, ctx, ctxlen)) {
    fprintf (stderr, "verify sig_2 failed!\n");
    return 7;
  }

  printf("Signature (%d): ", MLDSA_size);
  for (int n = 0; n < sizeof(sig.data); n++)
    printf ("%02x ", sig.data[n]);
  printf("\n");

  if (! MLDSA_keygen (&pub, NULL)) {
    fprintf (stderr, "keygen should have failed with NULL decaps\n");
    return 1;
  }
  if (! MLDSA_keygen (NULL, &priv)) {
    fprintf (stderr, "keygen should have failed with NULL encaps\n");
    return 1;
  }
  if (! MLDSA_keygen (NULL, NULL)) {
    fprintf (stderr, "keygen should have failed with NULL encaps and decaps\n");
    return 1;
  }

  if (! MLDSA_sign (NULL, msg, msglen, ctx, ctxlen, &sig_2)) {
    fprintf (stderr, "sign should have failed with NULL priv\n");
    return 1;
  }
  if (! MLDSA_sign (&priv, NULL, msglen, ctx, ctxlen, &sig_2)) {
    fprintf (stderr, "sign should have failed with NULL msg\n");
    return 1;
  }
  if (! MLDSA_sign (&priv, msg, msglen, NULL, ctxlen, &sig_2)) {
    fprintf (stderr, "sign should have failed with NULL ctx\n");
    return 1;
  }
  if (! MLDSA_sign (&priv, msg, msglen, ctx, ctxlen, NULL)) {
    fprintf (stderr, "sign should have failed with NULL sig_out\n");
    return 1;
  }
  if (MLDSA_sign (&priv, NULL, 0, ctx, ctxlen, &sig_2)) {
    fprintf (stderr, "sign should have succeeded with NULL and empty msg\n");
    return 1;
  }
  if (MLDSA_sign (&priv, msg, msglen, NULL, 0, &sig_2)) {
    fprintf (stderr, "sign should have succeeded with NULL and empty ctx\n");
    return 1;
  }

  if ((err = MLDSA_verify(&pub, &sig, msg, msglen, ctx, ctxlen))) {
    fprintf (stderr, "verify should have succeeeded! (got %d)\n", err);
    return 3;
  }
  if (! MLDSA_verify(&pub, &sig, msg, msglen, badctx, badctxlen)) {
    fprintf (stderr, "verify should have failed if the context changed\n");
    return 4;
  }
  if (! MLDSA_verify(&pub, &sig, badmsg, badmsglen, ctx, ctxlen)) {
    fprintf (stderr, "verify should have failed if the message changed\n");
    return 5;
  }
  sig.data[3]++;
  if (! MLDSA_verify(&pub, &sig, msg, msglen, ctx, ctxlen)) {
    fprintf (stderr, "verify should have failed if the signature was tampered with\n");
    return 6;
  }

  /* this ought to fail if BitUnpack aborts in skDecode, but it doesn't seem to.
     Is it possible that the parameters for ML-DSA-44 neatly avoid
     unrepresentable coefficients in this byte-representation? */
  for (int i = 0; i < sizeof(priv_weird.data); i++)
    priv_weird.data[i] = 0xff;
  err = MLDSA_sign (&priv_weird, msg, msglen, ctx, ctxlen, &sig);
  fprintf(stderr, "signing weird yielded %d\n", err);
#if 0
  if (err != ML_DSA_DESERIALIZATION_ERROR) {
    fprintf (stderr, "Signing with a private_key of all 0xff octets should have failed with deserialization error, got %d\n", err);
    return 1;
  }
#endif

  /* this ought to fail if BitUnpack aborts in pkDecode, but it
     doesn't seem to.  Is it possible that the parameters for
     ML-DSA-44 neatly avoid unrepresentable coefficients in this
     byte-representation? */
  for (int i = 0; i < sizeof(pub_weird.data); i++)
    pub_weird.data[i] = 0xff;
  err = MLDSA_verify (&pub_weird, &sig, msg, msglen, ctx, ctxlen);
  fprintf(stderr, "verifying weird yielded %d\n", err);
#if 0
  if (err != ML_DSA_DESERIALIZATION_ERROR) {
    fprintf (stderr, "Verification against a tampered public_key should have failed with deserialization error, got %d\n", err);
    return 1;
  } 
#endif
  
  return 0;
}
