[package]
name = "fips204-ct_cm4"
version = "0.4.4"
authors = ["Eric Schorn <eschorn@integritychain.com>"]
description = "Cortex-M4 testbench for FIPS 204 (draft) ML-DSA"
edition = "2021"
license = "MIT OR Apache-2.0"
publish = false
rust-version = "1.85"


[dependencies]
fips204 = { path = "..", default-features = false, features = ["ml-dsa-44"] }
cortex-m = { version = "0.7.7", features = ["critical-section-single-core"]}
cortex-m-rt = "0.7.3"
panic-rtt-target = { version =  "0.1.2", features = ["cortex-m"] }
microbit-v2 = "0.13.0"
rtt-target = { version = "0.5.0"}
rand_core = { version = "0.9", default-features = false }
hex-literal = "0.4.1"


[profile.dev]
debug = true
debug-assertions = false
overflow-checks = false
lto = true
opt-level = 3
codegen-units = 1
